name: Release
on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: true
        description: Commit SHA or version tag
permissions:
  contents: write
  actions: read
jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      ref: ${{ inputs.ref }}
